import type {
  BrandContext,
  ChannelType,
  ContentGenerationInput,
  GeneratedMessage,
} from "@/lib/ai/schemas";
import { buildEmailPrompt } from "@/lib/ai/prompts/content-email";
import { buildLandingPrompt } from "@/lib/ai/prompts/content-landing";
import { buildMetaAdPrompt } from "@/lib/ai/prompts/content-meta";
import { buildPushPrompt } from "@/lib/ai/prompts/content-push";
import { buildWhatsAppPrompt } from "@/lib/ai/prompts/content-whatsapp";

export type ContentWriterInput = {
  input: ContentGenerationInput;
  brandContext: BrandContext;
  recommendedAngle: string;
};

function selectPromptBuilder(channel: ChannelType) {
  if (channel === "meta") return buildMetaAdPrompt;
  if (channel === "email") return buildEmailPrompt;
  if (channel === "whatsapp") return buildWhatsAppPrompt;
  if (channel === "push") return buildPushPrompt;
  return buildLandingPrompt;
}

function headlineForVariant(
  input: ContentGenerationInput,
  recommendedAngle: string,
  variant: number,
): string {
  const audienceLead =
    input.audience === "client"
      ? "Confianza para resolver"
      : input.audience === "professional"
        ? "Trabajo serio para pros"
        : "Servicios claros para tu operacion";

  if (variant === 1) return `${audienceLead} con ${input.serviceCategory}`;
  if (variant === 2) return `${input.offer} con el respaldo de Handi`;
  return `${recommendedAngle.split(":")[0]} con Handi`;
}

function bodyForVariant(
  input: ContentGenerationInput,
  recommendedAngle: string,
  variant: number,
): string {
  const clientBodies = [
    `Encuentra apoyo confiable para ${input.serviceCategory} con una experiencia mas clara, segura y facil de seguir. ${input.offer}.`,
    `Cuando necesitas ${input.serviceCategory}, Handi te ayuda a avanzar con pros de confianza y un proceso mas simple. ${input.offer}.`,
    `Haz que ${input.serviceCategory} se sienta menos pesado y mas manejable con una plataforma practica y confiable. ${input.offer}.`,
  ];
  const professionalBodies = [
    `Haz que tu experiencia en ${input.serviceCategory} llegue a clientes serios con una presentacion mas clara y profesional. ${input.offer}.`,
    `Handi te ayuda a convertir tu trabajo en oportunidades mas ordenadas y confiables dentro de ${input.serviceCategory}. ${input.offer}.`,
    `Lleva tu trabajo de ${input.serviceCategory} a una vitrina mas confiable y facil de activar. ${input.offer}.`,
  ];
  const businessBodies = [
    `Organiza ${input.serviceCategory} con una capa mas clara de confianza, seguimiento y proveedores confiables. ${input.offer}.`,
    `Reduce friccion operativa en ${input.serviceCategory} con una solucion moderna y util para equipos que necesitan orden. ${input.offer}.`,
    `Activa un flujo mas confiable para ${input.serviceCategory} con Handi. ${input.offer}.`,
  ];

  const source =
    input.audience === "client"
      ? clientBodies
      : input.audience === "professional"
        ? professionalBodies
        : businessBodies;

  return `${source[variant - 1]} ${recommendedAngle}`;
}

export function runContentWriter(args: ContentWriterInput): {
  prompt: string;
  variants: GeneratedMessage[];
} {
  const { input, brandContext, recommendedAngle } = args;
  const prompt = selectPromptBuilder(input.channel)({
    input,
    brandContext,
    recommendedAngle,
  });

  const variants: GeneratedMessage[] = [1, 2, 3].map((variant) => ({
    id: `${input.channel}-${variant}`,
    label: `Variant ${variant}`,
    channel: input.channel,
    format: input.format,
    angle: recommendedAngle,
    headline: headlineForVariant(input, recommendedAngle, variant),
    body: bodyForVariant(input, recommendedAngle, variant),
    cta: input.cta,
    rationale:
      variant === 1
        ? "Leads with trust and category clarity."
        : variant === 2
          ? "Leads with the offer and brand reassurance."
          : "Leads with a broader Handi angle for variety.",
    prompt,
    guardrailsApplied: [
      ...brandContext.languageRules,
      ...brandContext.channelRules.doList,
      ...brandContext.channelRules.dontList,
      ...brandContext.channelRules.ctaRules,
    ],
    providerMetadata: {
      providerName: "mock",
      generationMode: "mock",
      model: null,
      generatedAt: new Date().toISOString(),
      fallbackReason: null,
      requestId: null,
      note: "Generated by internal content-writer agent.",
    },
  }));

  return { prompt, variants };
}
