import { Badge } from "@/components/ui/badge";

const MAP: Record<string, "default" | "secondary" | "destructive" | "outline"> =
  {
    active: "default",
    in_process: "secondary",
    cancelled: "destructive",
    canceled: "destructive",
    pending: "secondary",
    draft: "outline",
    proposed: "secondary",
    changes_requested: "secondary",
    approved: "default",
    rejected: "destructive",
    archived: "outline",
    not_ready: "outline",
    ready_to_publish: "secondary",
    publishing: "secondary",
    published: "default",
    publish_failed: "destructive",
    paused: "outline",
    queued: "outline",
    scheduled: "secondary",
    ready: "secondary",
    running: "secondary",
    completed: "default",
    healthy: "default",
    attention: "secondary",
    degraded: "destructive",
    recoverable_transient: "secondary",
    recoverable_rate_limited: "secondary",
    configuration_error: "destructive",
    readiness_error: "outline",
    approval_error: "outline",
    unsupported_channel: "outline",
    targeting_error: "outline",
    expired_window: "destructive",
    lock_conflict: "outline",
    unknown_error: "destructive",
    ready_for_review: "default",
    needs_attention: "secondary",
    high_risk: "destructive",
    low: "outline",
    medium: "secondary",
    high: "destructive",
    urgent: "destructive",
    candidate: "secondary",
    winner: "default",
    loser: "outline",
    insufficient_data: "outline",
    manual_only: "outline",
    not_supported: "outline",
    live: "default",
    mixed: "secondary",
    manual: "outline",
    limited: "outline",
    up: "default",
    down: "destructive",
    flat: "outline",
    paid: "default",
    refunded: "secondary",
    failed: "destructive",
  };

export default function StateBadge({ value }: { value: string }) {
  const v = (value || "").toLowerCase();
  return (
    <Badge variant={MAP[v] || "outline"}>{value.replace(/_/g, " ")}</Badge>
  );
}
