-- Add support_id to requests for shorter support references
alter table public.requests
  add column if not exists support_id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_class
    where relname = 'requests_support_id_fill_seq'
  ) then
    create sequence requests_support_id_fill_seq;
    perform setval(
      'requests_support_id_fill_seq',
      coalesce((select max(support_id) from public.requests), 0) + 1,
      false
    );
  end if;
end $$;

update public.requests
  set support_id = nextval('requests_support_id_fill_seq')
where support_id is null;

create unique index if not exists requests_support_id_unique
  on public.requests (support_id);

alter table public.requests
  alter column support_id set not null;

drop sequence if exists requests_support_id_fill_seq;
