name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pnpm + instalación (usa --frozen-lockfile)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
          install_command: |
            pnpm install --frozen-lockfile

      # Node (sin cache para evitar que pida package-lock/yarn.lock)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Si tus checks usan Playwright en Actions, instala browsers (no falla si no hay Playwright)
      - name: Install Playwright browsers
        run: npx playwright install --with-deps || true

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
