name: e2e

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9


      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Next.js
        run: pnpm build
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000

      - name: Start server
        run: |
          (pnpm start &)
          npx wait-on http://localhost:3000
        env:
          NODE_ENV: test
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          CI: "true"

      - name: Run E2E
        run: pnpm test:e2e:ci
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          CI: "true"
          PLAYWRIGHT_SKIP_WEBSERVER: "1"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
